// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-nocheck
import { getSafeApps, SafeAppData } from '@gnosis.pm/safe-react-gateway-sdk'

import { _getChainId } from 'src/config'
import { GATEWAY_URL } from 'src/utils/constants'

export const fetchSafeAppsList = async (): Promise<SafeAppData[]> => {
  console.log('fetchSafeAppsList')

  return [
    // {
    //   id: 18,
    //   url: 'https://app.aave.com',
    //   name: 'Aave v2',
    //   iconUrl: 'https://app.aave.com/aave.svg',
    //   description: 'Non-custodial liquidity protocol to earn interest on deposits and borrow',
    //   chainIds: ['1', '137'],
    //   provider: null,
    //   accessControl: { type: 'NO_RESTRICTIONS' },
    // },
    // {
    //   id: 11,
    //   url: 'https://apps.gnosis-safe.io/wallet-connect',
    //   name: 'WalletConnect',
    //   iconUrl: 'https://apps.gnosis-safe.io/wallet-connect/wallet-connect.svg',
    //   description: 'Connect your Safe to any dApp that supports WalletConnect',
    //   chainIds: ['1', '4', '5', '56', '10', '100', '137', '246', '42161', '43114', '73799', '1313161554'],
    //   provider: null,
    //   accessControl: { type: 'NO_RESTRICTIONS' },
    // },
    // {
    //   id: 13,
    //   url: 'https://cloudflare-ipfs.com/ipfs/QmSpfd5UwhUBZxKouqSsY3bFynyDy6sToVLigLwSWRms9s',
    //   name: 'Gnosis Auction Starter',
    //   iconUrl: 'https://cloudflare-ipfs.com/ipfs/QmSpfd5UwhUBZxKouqSsY3bFynyDy6sToVLigLwSWRms9s/logo.svg',
    //   description: 'Safe app to start new auctions on Gnosis Auction',
    //   chainIds: ['1', '4', '100', '137'],
    //   provider: null,
    //   accessControl: { type: 'NO_RESTRICTIONS' },
    // },
    // {
    //   id: 27,
    //   url: 'https://cloudflare-ipfs.com/ipfs/QmPsFDzB1M7kKi9UAdTRpETXAghCjFDEv6CMsd4Th4w68y',
    //   name: 'Sablier',
    //   iconUrl: 'https://cloudflare-ipfs.com/ipfs/QmPsFDzB1M7kKi9UAdTRpETXAghCjFDEv6CMsd4Th4w68y/logo.svg',
    //   description: 'Stream money with Sablier',
    //   chainIds: ['1', '4', '56', '137'],
    //   provider: { url: 'https://sablier.finance', name: 'Sablier' },
    //   accessControl: { type: 'NO_RESTRICTIONS' },
    // },
    // {
    //   id: 29,
    //   url: 'https://apps.gnosis-safe.io/tx-builder',
    //   name: 'Transaction Builder',
    //   iconUrl: 'https://apps.gnosis-safe.io/tx-builder/tx-builder.png',
    //   description: 'Compose custom contract interactions and batch them into a single transaction',
    //   chainIds: ['1', '4', '10', '56', '100', '137', '246', '42161', '43114', '73799', '1313161554'],
    //   provider: null,
    //   accessControl: { type: 'NO_RESTRICTIONS' },
    // },
    // {
    //   id: 1,
    //   url: 'https://app.dhedge.org/',
    //   name: 'dHEDGE',
    //   iconUrl: 'https://app.dhedge.org/logo.svg',
    //   description: 'Decentralized asset management',
    //   chainIds: ['1', '10', '137'],
    //   provider: { url: 'https://www.dhedge.org/', name: 'dHEDGE' },
    //   accessControl: { type: 'NO_RESTRICTIONS' },
    // },
    // {
    //   id: 40,
    //   url: 'https://quickswap.exchange/',
    //   name: 'QuickSwap',
    //   iconUrl: 'https://quickswap.exchange/logo_circle.png',
    //   description: 'QuickSwap',
    //   chainIds: ['137'],
    //   provider: { url: 'https://quickswap.exchange', name: 'QuickSwap' },
    //   accessControl: { type: 'NO_RESTRICTIONS' },
    // },
    // {
    //   id: 63,
    //   url: 'https://app.honeyswap.org',
    //   name: 'Honeyswap',
    //   iconUrl: 'https://app.honeyswap.org/images/512x512_App_Icon.png',
    //   description: 'Decentralized exchange built by 1Hive DAO',
    //   chainIds: ['100', '137'],
    //   provider: null,
    //   accessControl: { type: 'NO_RESTRICTIONS' },
    // },
    // {
    //   id: 62,
    //   url: 'https://banker.bulla.network',
    //   name: 'Bulla Banker',
    //   iconUrl: 'https://banker.bulla.network/logo192.png',
    //   description: 'A bankless Web3 accounting protocol for invoices and payments.',
    //   chainIds: ['4', '100', '137', '42161', '43114', '1313161554'],
    //   provider: null,
    //   accessControl: { type: 'NO_RESTRICTIONS' },
    // },
    // {
    //   id: 52,
    //   url: 'https://stakedao.org',
    //   name: 'StakeDAO',
    //   iconUrl: 'https://stakedao.org/images/logo.svg',
    //   description: 'Effortless ways to grow your crypto',
    //   chainIds: ['1', '137', '43114'],
    //   provider: null,
    //   accessControl: { type: 'NO_RESTRICTIONS' },
    // },
    // {
    //   id: 45,
    //   url: 'https://app.barnbridge.com',
    //   name: 'BarnBridge',
    //   iconUrl: 'https://app.barnbridge.com/logo.svg',
    //   description: 'Risk Tokenizing Protocol',
    //   chainIds: ['1', '137'],
    //   provider: { url: 'https://barnbridge.com/', name: 'BarnBridge' },
    //   accessControl: { type: 'NO_RESTRICTIONS' },
    // },
    // {
    //   id: 47,
    //   url: 'https://dapp.daohaus.club/',
    //   name: 'DAOhaus',
    //   iconUrl: 'https://dapp.daohaus.club/images/icons/icon-512x512.png',
    //   description: 'DAOhaus is a no code platform for Moloch DAOs.',
    //   chainIds: ['1', '4', '137', '100'],
    //   provider: null,
    //   accessControl: { type: 'NO_RESTRICTIONS' },
    // },
    // {
    //   id: 49,
    //   url: 'https://gnosis-zodiac-app.netlify.app/',
    //   name: 'Zodiac',
    //   iconUrl: 'https://gnosis-zodiac-app.netlify.app/zodiac-app-logo.png',
    //   description: 'The expansion pack for DAOs',
    //   chainIds: ['1', '4', '100', '137'],
    //   provider: null,
    //   accessControl: { type: 'NO_RESTRICTIONS' },
    // },
    // {
    //   id: 53,
    //   url: 'https://apy.plasma.finance',
    //   name: '0xPlasma Finance',
    //   iconUrl: 'https://apy.plasma.finance/logo.svg',
    //   description: 'Cross-chain DeFi & DEX aggregator, farming, asset management, fiat on-ramp',
    //   chainIds: ['1', '56', '137'],
    //   provider: null,
    //   accessControl: { type: 'NO_RESTRICTIONS' },
    // },
    // {
    //   id: 56,
    //   url: 'https://app.insurace.io/',
    //   name: 'InsurAce',
    //   iconUrl: 'https://app.insurace.io/logo.svg',
    //   description: 'Entry to the products and services InsurAce provides to secure your DeFi journey.',
    //   chainIds: ['1', '137', '56'],
    //   provider: null,
    //   accessControl: { type: 'NO_RESTRICTIONS' },
    // },
    {
      id: 35,
      url: 'https://app.sushi.com',
      name: 'Sushi',
      iconUrl: 'https://app.sushi.com/icons/icon-192x192.png',
      description:
        'Be a DeFi Chef with Sushi. Swap, earn, stack yields, lend, borrow, leverage all on one decentralized, community driven platform.',
      chainIds: ['1', '43113', '56', '42220', '250', '128', '137', '66', '100', '1666600000'],
      provider: { url: 'https://sushi.com/', name: 'SushiSwap' },
      accessControl: { type: 'NO_RESTRICTIONS' },
    },
    // {
    //   id: 37,
    //   url: 'https://app.request.finance',
    //   name: 'Request Invoicing',
    //   iconUrl: 'https://invoicing.request.network/logo512.png',
    //   description: 'The easiest way to get your invoices paid in crypto',
    //   chainIds: ['1', '4', '56', '100', '137', '42161'],
    //   provider: { url: 'https://request.network', name: 'Request' },
    //   accessControl: { type: 'NO_RESTRICTIONS' },
    // },
    // {
    //   id: 36,
    //   url: 'https://app.dodoex.io',
    //   name: 'DODO',
    //   iconUrl: 'https://dodoex.github.io/docs/DODO-media-kit/LOGO/Logo1-Y.png',
    //   description: 'DODO - Your on-chain liquidity provider.',
    //   chainIds: ['1', '4', '56', '137'],
    //   provider: { url: 'https://dodoex.io/', name: 'DODO' },
    //   accessControl: { type: 'NO_RESTRICTIONS' },
    // },
    // {
    //   id: 48,
    //   url: 'https://app.superfluid.finance/',
    //   name: 'Superfluid',
    //   iconUrl: 'https://app.superfluid.finance/icons/icon-96x96.png',
    //   description:
    //     'Superfluid is a new Ethereum Protocol that extends Ethereum tokens to include novel functionalities. Superfluid enables functionalities like money streaming and reward distribution.',
    //   chainIds: ['100', '137'],
    //   provider: null,
    //   accessControl: { type: 'NO_RESTRICTIONS' },
    // },
    // {
    //   id: 17,
    //   url: 'https://app.1inch.io',
    //   name: '1inch Network',
    //   iconUrl: 'https://app.1inch.io/assets/images/1inch_logo_without_text.svg',
    //   description: 'The most efficient defi aggregator',
    //   chainIds: ['1', '56', '100', '137'],
    //   provider: { url: 'https://1inch.exchange', name: '1inch corporation' },
    //   accessControl: { type: 'NO_RESTRICTIONS' },
    // },
    // {
    //   id: 33,
    //   url: 'https://cloudflare-ipfs.com/ipfs/Qme49gESuwpSvwANmEqo34yfCkzyQehooJ5yL7aHmKJnpZ',
    //   name: 'CSV Airdrop',
    //   iconUrl: 'https://cloudflare-ipfs.com/ipfs/Qme49gESuwpSvwANmEqo34yfCkzyQehooJ5yL7aHmKJnpZ/logo.svg',
    //   description:
    //     'Upload your CSV transfer file to send arbitrarily many tokens of various amounts to a list of recipients.',
    //   chainIds: ['1', '4', '100', '56', '137'],
    //   provider: null,
    //   accessControl: { type: 'NO_RESTRICTIONS' },
    // },
    // {
    //   id: 67,
    //   url: 'https://apps.gnosis-safe.io/ramp-network',
    //   name: 'Ramp',
    //   iconUrl: 'https://apps.gnosis-safe.io/ramp-network/ramp.svg',
    //   description: 'Buy BTC, ETH and more in minutes.',
    //   chainIds: ['1', '4', '56', '100', '137', '42161', '43114'],
    //   provider: null,
    //   accessControl: { type: 'NO_RESTRICTIONS' },
    // },
  ]
  // return getSafeApps(GATEWAY_URL, _getChainId(), {
  //   client_url: window.location.origin,
  // })
}
